sudo: required
Services:
    - docker

before_install:
    - docker build -t amaisenovich/dcm-frontend-test -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true amaisenovich/dcm-frontend-test npm test

after_success:
    - docker build -t amaisenovich/dcm-backend ./backend
    - docker build -t amaisenovich/dcm-frontend ./frontend
    - docker build -t amaisenovich/dcm-nginx ./nginx
    - docker build -t amaisenovich/dcm-worker ./worker
    - echo "$DOCKER_PAT" | docker login --username "$DOCKER_ID" --password-stdin
    - docker push amaisenovich/dcm-backend
    - docker push amaisenovich/dcm-frontend
    - docker push amaisenovich/dcm-nginx
    - docker push amaisenovich/dcm-worker

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "dcm"
    env: "Dcm-env"
    bucket_name: "elasticbeanstalk-eu-central-1-830776640802"
    bucket_path: "dcm"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
