version: '3'
services:
    postgres:
        image: postgres:alpine

    redis:
        image: redis:alpine

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - 8080:80
        restart: always

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./backend:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432

    frontend:
       build:
           context: ./frontend
           dockerfile: Dockerfile.dev
       volumes:
           - /app/node_modules
           - ./frontend:/app

    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
